version: '3'
services:
  fr-api:
    container_name: fr-api
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./data/all_listings.csv:/usr/src/app/data/all_listings.csv
    depends_on:
      - mongodb
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      API_PORT: 4000
    command: sh -c "npm run serve || tail -f /dev/null"
  mongodb:
    container_name: frDb
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    ports:
      - "${DATABASE_PORT}:27017"
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    restart: always


volumes:
  mongodb_data_container:
