version: '3'
services:
  mongodb:
    container_name: frDb
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
      - ${DATABASE_PORT}:27017
    volumes:
      - mongodb_data_container:/data/db
    env_file:
      - ".env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    restart: always

volumes:
  mongodb_data_container:
